mode="client"

certFile="/etc/bridgeburner/certs/VIJAY/clients/VJ-backup-automation.crt"
keyFile="/etc/bridgeburner/certs/VIJAY/clients/VJ-backup-automation.key"
caFile="/etc/bridgeburner/certs/VIJAY/CA.crt"

[client]
    serverAddress="10.100.249.47:7000"

    [[client.services]]
    Name="2812ea87-4116-4e83-b8cc-8687cf129972"
    Address="10.100.249.44"
    Port=8000
    Protocol="http"

[logging]
level="info"
