deadbolt:
  DEADBOLT_CLIENT_ID: ''
  DEADBOLT_CLIENT_SECRET: ''
  DEADBOLT_IP: ''
  DEADBOLT_PORT: 8080
middleware_service_details:
  password: ''
  username: ''
rabbitmq:
  RABBIT_MQ_IP: ''
  RABBIT_MQ_PASSWORD: ''
  RABBIT_MQ_USERNAME: ''
workers:
  no_of_proc: 3
