consul:
  CONSUL_IP: ''
  CONSUL_PORT: '8500'
log:
  backupcount: 2
  filename: /var/log/middleware/worker.log
  level: info
  maxbytes: 5242880
rabbitmq:
  RABBIT_MQ_IP: ''
  RABBIT_MQ_PASSWORD: ''
  RABBIT_MQ_USERNAME: ''
servicenow:
  SERVICENOW_USERNAME: ''
  SERVICENOW_PASSWORD: ''
vulnerability:
  VSCAN_SERVER_PASSWORD: ''
  VSCAN_SERVER_URL: ''
  VSCAN_SERVER_USERNAME: ''
workers:
  no_of_proc: 3
xstream:
  XSTREAM_KEY: ''
  XSTREAM_SECRET: ''
